// <auto-generated />
using ChargesProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ChargesProject.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20180616125153_Charges1")]
    partial class Charges1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChargesProject.Models.Charges", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Gas");

                    b.Property<string>("LoansInstall");

                    b.Property<string>("PhoneBill");

                    b.Property<string>("Rent");

                    b.HasKey("Id");

                    b.ToTable("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
